### ISSUE TITLE
Problem parsing IdleTime

### ISSUE THREAD

**Issue by gersonagc** [jeremysprite/ps-quser#1]
Hi! Thanks for sharing this script! :)

There is a better way to parse this information. I changed the equivalent line to:

`$quserData[5] = $quserData[5] -replace "\.","0:0" -replace "Disc","0:0" -replace "\+","."`

1. the order of "replaces" is important.
2. replacing "+" with a "." makes the code works with intervals smaller than 24 days. [timespan] deals with it.

**Comment by sysadmin-as-a-service** [comment]
Hi @gersonagc, apologies its taken me this long to see your issue. Will adjust script in a couple of days - thanks!

**Comment by sysadmin-as-a-service** [comment]
Should be sorted now, have updated in #2 

Thanks!
